// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Buy_expansion;
using Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Deposit;
using Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Withdraw;
namespace Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank
{
    /// <summary>
    /// Builds and executes requests for operations under \my\{name}\action\bank
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BankRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The buy_expansion property</summary>
        public global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Buy_expansion.Buy_expansionRequestBuilder Buy_expansion
        {
            get => new global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Buy_expansion.Buy_expansionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deposit property</summary>
        public global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Deposit.DepositRequestBuilder Deposit
        {
            get => new global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Deposit.DepositRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The withdraw property</summary>
        public global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Withdraw.WithdrawRequestBuilder Withdraw
        {
            get => new global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.Withdraw.WithdrawRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.BankRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/{name}/action/bank", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.My.Item.ActionNamespace.Bank.BankRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/{name}/action/bank", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
