// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Zeno.Artifacts.Shared.Client.Characters.Create;
using Zeno.Artifacts.Shared.Client.Characters.Delete;
using Zeno.Artifacts.Shared.Client.Characters.Item;
namespace Zeno.Artifacts.Shared.Client.Characters
{
    /// <summary>
    /// Builds and executes requests for operations under \characters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CharactersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Zeno.Artifacts.Shared.Client.Characters.Create.CreateRequestBuilder Create
        {
            get => new global::Zeno.Artifacts.Shared.Client.Characters.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Zeno.Artifacts.Shared.Client.Characters.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Zeno.Artifacts.Shared.Client.Characters.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the zeno.artifacts.shared.client.characters.item collection</summary>
        /// <param name="position">The character name.</param>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Characters.Item.WithNameItemRequestBuilder"/></returns>
        public global::Zeno.Artifacts.Shared.Client.Characters.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::Zeno.Artifacts.Shared.Client.Characters.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Characters.CharactersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CharactersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Characters.CharactersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CharactersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
