// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Achievement points.</summary>
        public int? AchievementsPoints { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Account badges.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Badges { get; set; }
#nullable restore
#else
        public UntypedNode Badges { get; set; }
#endif
        /// <summary>Banned.</summary>
        public bool? Banned { get; set; }
        /// <summary>Ban reason.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BanReason { get; set; }
#nullable restore
#else
        public string BanReason { get; set; }
#endif
        /// <summary>Member status.</summary>
        public bool? Member { get; set; }
        /// <summary>Skins owned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Skins { get; set; }
#nullable restore
#else
        public UntypedNode Skins { get; set; }
#endif
        /// <summary>Account status.</summary>
        public global::Zeno.Artifacts.Shared.Client.Models.AccountStatus? Status { get; set; }
        /// <summary>Username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.AccountDetails"/> and sets the default values.
        /// </summary>
        public AccountDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.AccountDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.AccountDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.AccountDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "achievements_points", n => { AchievementsPoints = n.GetIntValue(); } },
                { "badges", n => { Badges = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "ban_reason", n => { BanReason = n.GetStringValue(); } },
                { "banned", n => { Banned = n.GetBoolValue(); } },
                { "member", n => { Member = n.GetBoolValue(); } },
                { "skins", n => { Skins = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Zeno.Artifacts.Shared.Client.Models.AccountStatus>(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("achievements_points", AchievementsPoints);
            writer.WriteObjectValue<UntypedNode>("badges", Badges);
            writer.WriteBoolValue("banned", Banned);
            writer.WriteStringValue("ban_reason", BanReason);
            writer.WriteBoolValue("member", Member);
            writer.WriteObjectValue<UntypedNode>("skins", Skins);
            writer.WriteEnumValue<global::Zeno.Artifacts.Shared.Client.Models.AccountStatus>("status", Status);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
