// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CooldownSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The expiration of the cooldown.</summary>
        public DateTimeOffset? Expiration { get; set; }
        /// <summary>The reason of the cooldown.</summary>
        public global::Zeno.Artifacts.Shared.Client.Models.ActionType? Reason { get; set; }
        /// <summary>The remaining seconds of the cooldown.</summary>
        public int? RemainingSeconds { get; set; }
        /// <summary>The start of the cooldown.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The total seconds of the cooldown.</summary>
        public int? TotalSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema"/> and sets the default values.
        /// </summary>
        public CooldownSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expiration", n => { Expiration = n.GetDateTimeOffsetValue(); } },
                { "reason", n => { Reason = n.GetEnumValue<global::Zeno.Artifacts.Shared.Client.Models.ActionType>(); } },
                { "remaining_seconds", n => { RemainingSeconds = n.GetIntValue(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "total_seconds", n => { TotalSeconds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("expiration", Expiration);
            writer.WriteEnumValue<global::Zeno.Artifacts.Shared.Client.Models.ActionType>("reason", Reason);
            writer.WriteIntValue("remaining_seconds", RemainingSeconds);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteIntValue("total_seconds", TotalSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
