// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeleteItemSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Player details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Zeno.Artifacts.Shared.Client.Models.CharacterSchema? Character { get; set; }
#nullable restore
#else
        public global::Zeno.Artifacts.Shared.Client.Models.CharacterSchema Character { get; set; }
#endif
        /// <summary>Cooldown details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema? Cooldown { get; set; }
#nullable restore
#else
        public global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema Cooldown { get; set; }
#endif
        /// <summary>Item details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Zeno.Artifacts.Shared.Client.Models.SimpleItemSchema? Item { get; set; }
#nullable restore
#else
        public global::Zeno.Artifacts.Shared.Client.Models.SimpleItemSchema Item { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.DeleteItemSchema"/> and sets the default values.
        /// </summary>
        public DeleteItemSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.DeleteItemSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.DeleteItemSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.DeleteItemSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "character", n => { Character = n.GetObjectValue<global::Zeno.Artifacts.Shared.Client.Models.CharacterSchema>(global::Zeno.Artifacts.Shared.Client.Models.CharacterSchema.CreateFromDiscriminatorValue); } },
                { "cooldown", n => { Cooldown = n.GetObjectValue<global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema>(global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema.CreateFromDiscriminatorValue); } },
                { "item", n => { Item = n.GetObjectValue<global::Zeno.Artifacts.Shared.Client.Models.SimpleItemSchema>(global::Zeno.Artifacts.Shared.Client.Models.SimpleItemSchema.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.CharacterSchema>("character", Character);
            writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.CooldownSchema>("cooldown", Cooldown);
            writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.SimpleItemSchema>("item", Item);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
