// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FightSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items dropped from the fight.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Zeno.Artifacts.Shared.Client.Models.DropSchema>? Drops { get; set; }
#nullable restore
#else
        public List<global::Zeno.Artifacts.Shared.Client.Models.DropSchema> Drops { get; set; }
#endif
        /// <summary>The amount of gold gained from the fight.</summary>
        public int? Gold { get; set; }
        /// <summary>The fight logs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Logs { get; set; }
#nullable restore
#else
        public List<string> Logs { get; set; }
#endif
        /// <summary>The result of the fight.</summary>
        public global::Zeno.Artifacts.Shared.Client.Models.FightResult? Result { get; set; }
        /// <summary>Numbers of the turns of the combat.</summary>
        public int? Turns { get; set; }
        /// <summary>The amount of xp gained from the fight.</summary>
        public int? Xp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.FightSchema"/> and sets the default values.
        /// </summary>
        public FightSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.FightSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.FightSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.FightSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "drops", n => { Drops = n.GetCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.DropSchema>(global::Zeno.Artifacts.Shared.Client.Models.DropSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gold", n => { Gold = n.GetIntValue(); } },
                { "logs", n => { Logs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "result", n => { Result = n.GetEnumValue<global::Zeno.Artifacts.Shared.Client.Models.FightResult>(); } },
                { "turns", n => { Turns = n.GetIntValue(); } },
                { "xp", n => { Xp = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.DropSchema>("drops", Drops);
            writer.WriteIntValue("gold", Gold);
            writer.WriteCollectionOfPrimitiveValues<string>("logs", Logs);
            writer.WriteEnumValue<global::Zeno.Artifacts.Shared.Client.Models.FightResult>("result", Result);
            writer.WriteIntValue("turns", Turns);
            writer.WriteIntValue("xp", Xp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
