// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MyAccountDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Achievement points.</summary>
        public int? AchievementsPoints { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Account badges.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Badges { get; set; }
#nullable restore
#else
        public UntypedNode Badges { get; set; }
#endif
        /// <summary>Banned.</summary>
        public bool? Banned { get; set; }
        /// <summary>Ban reason.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BanReason { get; set; }
#nullable restore
#else
        public string BanReason { get; set; }
#endif
        /// <summary>Email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Gems.</summary>
        public int? Gems { get; set; }
        /// <summary>Member status.</summary>
        public bool? Member { get; set; }
        /// <summary>Member expiration date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration? MemberExpiration { get; set; }
#nullable restore
#else
        public global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration MemberExpiration { get; set; }
#endif
        /// <summary>Skins owned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Skins { get; set; }
#nullable restore
#else
        public UntypedNode Skins { get; set; }
#endif
        /// <summary>Account status.</summary>
        public global::Zeno.Artifacts.Shared.Client.Models.AccountStatus? Status { get; set; }
        /// <summary>Username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails"/> and sets the default values.
        /// </summary>
        public MyAccountDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "achievements_points", n => { AchievementsPoints = n.GetIntValue(); } },
                { "badges", n => { Badges = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "ban_reason", n => { BanReason = n.GetStringValue(); } },
                { "banned", n => { Banned = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "gems", n => { Gems = n.GetIntValue(); } },
                { "member", n => { Member = n.GetBoolValue(); } },
                { "member_expiration", n => { MemberExpiration = n.GetObjectValue<global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration>(global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration.CreateFromDiscriminatorValue); } },
                { "skins", n => { Skins = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Zeno.Artifacts.Shared.Client.Models.AccountStatus>(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("achievements_points", AchievementsPoints);
            writer.WriteObjectValue<UntypedNode>("badges", Badges);
            writer.WriteBoolValue("banned", Banned);
            writer.WriteStringValue("ban_reason", BanReason);
            writer.WriteStringValue("email", Email);
            writer.WriteIntValue("gems", Gems);
            writer.WriteBoolValue("member", Member);
            writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration>("member_expiration", MemberExpiration);
            writer.WriteObjectValue<UntypedNode>("skins", Skins);
            writer.WriteEnumValue<global::Zeno.Artifacts.Shared.Client.Models.AccountStatus>("status", Status);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MyAccountDetails_member_expiration : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1? MyAccountDetailsMemberExpirationMember1 { get; set; }
#nullable restore
#else
            public global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1 MyAccountDetailsMemberExpirationMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails.MyAccountDetails_member_expiration();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.MyAccountDetailsMemberExpirationMember1 = new global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MyAccountDetailsMemberExpirationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MyAccountDetailsMemberExpirationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.MyAccountDetails_member_expirationMember1>(null, MyAccountDetailsMemberExpirationMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
