// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Zeno.Artifacts.Shared.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatusSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Server announcements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Zeno.Artifacts.Shared.Client.Models.AnnouncementSchema>? Announcements { get; set; }
#nullable restore
#else
        public List<global::Zeno.Artifacts.Shared.Client.Models.AnnouncementSchema> Announcements { get; set; }
#endif
        /// <summary>Characters online.</summary>
        public int? CharactersOnline { get; set; }
        /// <summary>Maximum level.</summary>
        public int? MaxLevel { get; set; }
        /// <summary>Maximum skill level.</summary>
        public int? MaxSkillLevel { get; set; }
        /// <summary>Rate limits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Zeno.Artifacts.Shared.Client.Models.RateLimitSchema>? RateLimits { get; set; }
#nullable restore
#else
        public List<global::Zeno.Artifacts.Shared.Client.Models.RateLimitSchema> RateLimits { get; set; }
#endif
        /// <summary>Current season details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Zeno.Artifacts.Shared.Client.Models.SeasonSchema? Season { get; set; }
#nullable restore
#else
        public global::Zeno.Artifacts.Shared.Client.Models.SeasonSchema Season { get; set; }
#endif
        /// <summary>Server time.</summary>
        public DateTimeOffset? ServerTime { get; set; }
        /// <summary>Game version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Models.StatusSchema"/> and sets the default values.
        /// </summary>
        public StatusSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.StatusSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Zeno.Artifacts.Shared.Client.Models.StatusSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Zeno.Artifacts.Shared.Client.Models.StatusSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "announcements", n => { Announcements = n.GetCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.AnnouncementSchema>(global::Zeno.Artifacts.Shared.Client.Models.AnnouncementSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "characters_online", n => { CharactersOnline = n.GetIntValue(); } },
                { "max_level", n => { MaxLevel = n.GetIntValue(); } },
                { "max_skill_level", n => { MaxSkillLevel = n.GetIntValue(); } },
                { "rate_limits", n => { RateLimits = n.GetCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.RateLimitSchema>(global::Zeno.Artifacts.Shared.Client.Models.RateLimitSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "season", n => { Season = n.GetObjectValue<global::Zeno.Artifacts.Shared.Client.Models.SeasonSchema>(global::Zeno.Artifacts.Shared.Client.Models.SeasonSchema.CreateFromDiscriminatorValue); } },
                { "server_time", n => { ServerTime = n.GetDateTimeOffsetValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.AnnouncementSchema>("announcements", Announcements);
            writer.WriteIntValue("characters_online", CharactersOnline);
            writer.WriteIntValue("max_level", MaxLevel);
            writer.WriteIntValue("max_skill_level", MaxSkillLevel);
            writer.WriteCollectionOfObjectValues<global::Zeno.Artifacts.Shared.Client.Models.RateLimitSchema>("rate_limits", RateLimits);
            writer.WriteObjectValue<global::Zeno.Artifacts.Shared.Client.Models.SeasonSchema>("season", Season);
            writer.WriteDateTimeOffsetValue("server_time", ServerTime);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
