// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Zeno.Artifacts.Shared.Client.Accounts.Create;
using Zeno.Artifacts.Shared.Client.Accounts.Forgot_password;
using Zeno.Artifacts.Shared.Client.Accounts.Item;
using Zeno.Artifacts.Shared.Client.Accounts.Reset_password;
namespace Zeno.Artifacts.Shared.Client.Accounts
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Zeno.Artifacts.Shared.Client.Accounts.Create.CreateRequestBuilder Create
        {
            get => new global::Zeno.Artifacts.Shared.Client.Accounts.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgot_password property</summary>
        public global::Zeno.Artifacts.Shared.Client.Accounts.Forgot_password.Forgot_passwordRequestBuilder Forgot_password
        {
            get => new global::Zeno.Artifacts.Shared.Client.Accounts.Forgot_password.Forgot_passwordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset_password property</summary>
        public global::Zeno.Artifacts.Shared.Client.Accounts.Reset_password.Reset_passwordRequestBuilder Reset_password
        {
            get => new global::Zeno.Artifacts.Shared.Client.Accounts.Reset_password.Reset_passwordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the zeno.artifacts.shared.client.accounts.item collection</summary>
        /// <param name="position">The account name.</param>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Accounts.Item.WithAccountItemRequestBuilder"/></returns>
        public global::Zeno.Artifacts.Shared.Client.Accounts.Item.WithAccountItemRequestBuilder this[string position]
        {
            get
            {   
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("account", position);
                return new global::Zeno.Artifacts.Shared.Client.Accounts.Item.WithAccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
