// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Zeno.Artifacts.Shared.Client.Accounts;
using Zeno.Artifacts.Shared.Client.Achievements;
using Zeno.Artifacts.Shared.Client.Badges;
using Zeno.Artifacts.Shared.Client.Characters;
using Zeno.Artifacts.Shared.Client.Effects;
using Zeno.Artifacts.Shared.Client.Events;
using Zeno.Artifacts.Shared.Client.Grandexchange;
using Zeno.Artifacts.Shared.Client.Items;
using Zeno.Artifacts.Shared.Client.Leaderboard;
using Zeno.Artifacts.Shared.Client.Maps;
using Zeno.Artifacts.Shared.Client.Models;
using Zeno.Artifacts.Shared.Client.Monsters;
using Zeno.Artifacts.Shared.Client.My;
using Zeno.Artifacts.Shared.Client.Npcs;
using Zeno.Artifacts.Shared.Client.Resources;
using Zeno.Artifacts.Shared.Client.Tasks;
using Zeno.Artifacts.Shared.Client.Token;
using Microsoft.Graph;
namespace Zeno.Artifacts.Shared.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArtifactsApiClient : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Zeno.Artifacts.Shared.Client.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Zeno.Artifacts.Shared.Client.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The achievements property</summary>
        public global::Zeno.Artifacts.Shared.Client.Achievements.AchievementsRequestBuilder Achievements
        {
            get => new global::Zeno.Artifacts.Shared.Client.Achievements.AchievementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The badges property</summary>
        public global::Zeno.Artifacts.Shared.Client.Badges.BadgesRequestBuilder Badges
        {
            get => new global::Zeno.Artifacts.Shared.Client.Badges.BadgesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The characters property</summary>
        public global::Zeno.Artifacts.Shared.Client.Characters.CharactersRequestBuilder Characters
        {
            get => new global::Zeno.Artifacts.Shared.Client.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The effects property</summary>
        public global::Zeno.Artifacts.Shared.Client.Effects.EffectsRequestBuilder Effects
        {
            get => new global::Zeno.Artifacts.Shared.Client.Effects.EffectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Zeno.Artifacts.Shared.Client.Events.EventsRequestBuilder Events
        {
            get => new global::Zeno.Artifacts.Shared.Client.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The grandexchange property</summary>
        public global::Zeno.Artifacts.Shared.Client.Grandexchange.GrandexchangeRequestBuilder Grandexchange
        {
            get => new global::Zeno.Artifacts.Shared.Client.Grandexchange.GrandexchangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Zeno.Artifacts.Shared.Client.Items.ItemsRequestBuilder Items
        {
            get => new global::Zeno.Artifacts.Shared.Client.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leaderboard property</summary>
        public global::Zeno.Artifacts.Shared.Client.Leaderboard.LeaderboardRequestBuilder Leaderboard
        {
            get => new global::Zeno.Artifacts.Shared.Client.Leaderboard.LeaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maps property</summary>
        public global::Zeno.Artifacts.Shared.Client.Maps.MapsRequestBuilder Maps
        {
            get => new global::Zeno.Artifacts.Shared.Client.Maps.MapsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The monsters property</summary>
        public global::Zeno.Artifacts.Shared.Client.Monsters.MonstersRequestBuilder Monsters
        {
            get => new global::Zeno.Artifacts.Shared.Client.Monsters.MonstersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The my property</summary>
        public global::Zeno.Artifacts.Shared.Client.My.MyRequestBuilder My
        {
            get => new global::Zeno.Artifacts.Shared.Client.My.MyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The npcs property</summary>
        public global::Zeno.Artifacts.Shared.Client.Npcs.NpcsRequestBuilder Npcs
        {
            get => new global::Zeno.Artifacts.Shared.Client.Npcs.NpcsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resources property</summary>
        public global::Zeno.Artifacts.Shared.Client.Resources.ResourcesRequestBuilder Resources
        {
            get => new global::Zeno.Artifacts.Shared.Client.Resources.ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Zeno.Artifacts.Shared.Client.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Zeno.Artifacts.Shared.Client.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Zeno.Artifacts.Shared.Client.Token.TokenRequestBuilder Token
        {
            get => new global::Zeno.Artifacts.Shared.Client.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zeno.Artifacts.Shared.Client.ArtifactsApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ArtifactsApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
        /// <summary>
        /// Return the status of the game server.
        /// </summary>
        /// <returns>A <see cref="global::Zeno.Artifacts.Shared.Client.Models.StatusResponseSchema"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zeno.Artifacts.Shared.Client.Models.StatusResponseSchema?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zeno.Artifacts.Shared.Client.Models.StatusResponseSchema> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zeno.Artifacts.Shared.Client.Models.StatusResponseSchema>(requestInfo, global::Zeno.Artifacts.Shared.Client.Models.StatusResponseSchema.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return the status of the game server.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ArtifactsApiClientGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
